export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const GET_USER_ORDERS_REQUEST = 'GET_USER_ORDERS_REQUEST';
export const GET_USER_ORDERS_SUCCESS = 'GET_USER_ORDERS_SUCCESS';
export const GET_USER_ORDERS_FAIL = 'GET_USER_ORDERS_FAIL';

export const SET_SELECTED_ITEMS = 'SET_SELECTED_ITEMS';
export const SET_PAYMENT_METHOD = 'SET_PAYMENT_METHOD';
export const CLEAR_ORDER_STATE = 'CLEAR_ORDER_STATE';
