export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const PRODUCT_REVIEWS_REQUEST = 'PRODUCT_REVIEWS_REQUEST';
export const PRODUCT_REVIEWS_SUCCESS = 'PRODUCT_REVIEWS_SUCCESS';
export const PRODUCT_REVIEWS_FAIL = 'PRODUCT_REVIEWS_FAIL';